config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'pages#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :teams, only:[:index]
  get 'dashboard' , to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def dashboard
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
      @teams=Team.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end

end

app/helpers/pages_helper.rb
module PagesHelper

  def show_svg(path)
    File.open("app/assets/images/#{path}", "rb") do |file|
      raw file.read
    end
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>

  <div class="header_bg">

    <div class="container header_content">

        <%= link_to dashboard_path, class: "header_left_content" do %>
          <%= show_svg('logo-roster.svg') %>
        <% end %>

        <div class="header_center_content">

          <%= content_tag :div, :class => ["center-menu-entry", current_class?(dashboard_path)] do -%>
            <%= link_to dashboard_path, class: "btn-menu" do %>
              <%= show_svg('icon-home.svg') %>
            <% end %>
          <% end %>

          <%= content_tag :div, :class => ["center-menu-entry", current_class?(teams_path)] do -%>
            <%= link_to teams_path, class: "btn-menu" do %>
              <%= show_svg('icon-teams.svg') %>
            <% end %>
          <% end %>

          <%= content_tag :div, :class => ["center-menu-entry", current_class?(teams_path)] do -%>
            <%= link_to teams_path, class: "btn-menu" do %>
              <%= show_svg('icon-fixtures.svg') %>
            <% end %>
          <% end %>

          <%= content_tag :div, :class => ["center-menu-entry", current_class?(teams_path)] do -%>
            <%= link_to teams_path, class: "btn-menu" do %>
              <%= show_svg('icon-bookmarks.svg') %>
            <% end %>
          <% end %>

          <%= content_tag :div, :class => ["center-menu-entry", current_class?(teams_path)] do -%>
            <%= link_to teams_path, class: "btn-menu" do %>
              <%= show_svg('icon-stats.svg') %>
            <% end %>
          <% end %>

        </div>

        <div class="header_right_content">

            <%= link_to edit_user_registration_path, class: "btn_avatar" do %>
              Matthieu
              <div class="circle picture">
                <%= current_user.email[0,1].capitalize %>
              </div>
            <% end %>

          <%= link_to destroy_user_session_path, method: :delete, class: "circle btn_header_action" do %>
            <%= show_svg('icon-logout.svg') %>
          <% end %>

        </div>

    </div>

  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.svg') %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= yield %>

    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h2>
    <center>
      You have no team nor activity
    </center>
  </h2>
</div>